server:
    port: 8080
spring:
  profiles:
    active: prod
logging:
  file:
    name: ./logs/mytest.log
  #level:
    #root: "INFO"
    #org.springframework: "INFO"
    #com.test.myapp.controllers: "ERROR"
  #pattern:
    #console : "[%d{yy-MM-dd HH:mm:ss:SSS}][%-5p][%c][%t]%m%n"
    #file : "[%d{yy-MM-dd HH:mm:ss:SSS}][%-5p][%c][%t]%m%n" #file is zipped
  logback:
    rollingpolicy:
      max-history : 15 #num of days
      max-file-size : 10KB
      file-name-pattern : "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  datasource:
      driverClassName: org.postgresql.Driver
      #applied in profiles
      #url: jdbc:postgresql://postgres:5432/dev
      #username: dev
      #password: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    #defaultSchema: dev
    #user: dev
    #password: dev
